### ISSUE TITLE
allow user to keep scrolling and loading more videos

### ISSUE THREAD

**Issue by IanWalston** [callbacc/Artistify#49]

**Comment by gregoriB** [comment]
I'm not sure if this is actually possible with yt-search.  I made a [simple implementation](https://github.com/gregoriB/Artistify/tree/feature/endless-scrolling) but the issue is yt-search is basically web scraping search results from youtube and pagination doesn't work as intended.

**Comment by callbacc** [comment]
We will for sure take a look at it! Thanks for the time spent on it!

**Comment by IanWalston** [comment]
maybe we should make a PR to `yt-search` and try to fix it there

**Comment by gregoriB** [comment]
There is this [issue](https://github.com/talmobi/yt-search/issues/7), which seems related.  I'm not too sure what the deal is there, but he suggested a different library so I updated [my fork](https://github.com/gregoriB/Artistify/tree/feature/endless-scrolling) to use it and pagination seems to be working well.

If someone wants to create a feature branch I can make a PR and merge into it.  Or I can make a PR to merge into develop instead, but currently video playback doesn't work in my branch so that doesn't seem ideal.  I'm kind of out of time and won't be able to contribute further.

**Comment by IanWalston** [comment]
thanks! I will probably use your backend changes and just hook the frontend part myself since a lot has changed and you said it's not currenlty working!
